version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html  # persist frontend files
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    volumes:
      - ./backend:/app  # persist backend code
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # persist metrics data
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana  # persist dashboards/configs
    restart: always

volumes:
  prometheus_data:
  grafana_data:




